TOTAL_RUNS=30
for ((i=45; i<=TOTAL_RUNS+45; i++))
do

  echo "===> 第 $i 轮训练开始 训练: dataset = LLCM"
  # LLCM adr
  python train_adr.py --config_file configs/LLCM/LLCM_adr.yml MODEL.DEVICE_ID "('0')" OUTPUT_DIR 'logs/llcm_ADR' SOLVER.BASE_LR 0.008 SOLVER.EVAL_PERIOD 1 INPUT.AUG 2 \
  INPUT.SIZE_TRAIN [256,128] INPUT.SIZE_TEST [256,128] MODEL.MSEL True MODEL.MSEL_EPOCH 10 DATASETS.SAMPLER 'modal' MODEL.MSEL_MODAL True DATALOADER.NUM_INSTANCE 8 \
  MODEL.USE_PROMPT True MODEL.NUM_TOKEN 16 MODEL.PROMPT_SCALE 20.0 MODEL.PROMPT_SHIFT 0.0 MODEL.USE_INS_PROMPT True MODEL.USE_INS_PROMPT_GEN True MODEL.NUM_INS_PMT_TOKEN 16 \
  SOLVER.WEIGHT_IPLR 15.0 SOLVER.WEIGHT_MPLR 5.0 MODEL.IPIL False SOLVER.MAX_EPOCHS 80 TEST.EVAL_EPOCH 10 SOLVER.SCHEDULER 'cosine-refine' SOLVER.MIN_INDEX 0.00001 SOLVER.COSINE_EPOCHS 40 SOLVER.SEED $i


  echo "===> 第 $i 轮训练开始 训练: dataset = SYSU-MM01"
  # SYSU adr
  python train_adr.py --config_file configs/SYSU-MM/SYSU_adr.yml MODEL.DEVICE_ID "('0')" OUTPUT_DIR 'logs/sysu_ADR' SOLVER.BASE_LR 0.012 SOLVER.EVAL_PERIOD 1 INPUT.AUG 2 \
  INPUT.SIZE_TRAIN [256,128] INPUT.SIZE_TEST [256,128] MODEL.MSEL True MODEL.MSEL_EPOCH 10 DATASETS.SAMPLER 'modal' MODEL.MSEL_MODAL True DATALOADER.NUM_INSTANCE 8 \
  MODEL.USE_PROMPT True MODEL.NUM_TOKEN 16 MODEL.PROMPT_SCALE 20.0 MODEL.PROMPT_SHIFT 0.0 MODEL.USE_INS_PROMPT True MODEL.USE_INS_PROMPT_GEN True MODEL.NUM_INS_PMT_TOKEN 16 \
  SOLVER.WEIGHT_IPLR 15.0 SOLVER.WEIGHT_MPLR 5.0 MODEL.IPIL False SOLVER.MAX_EPOCHS 80 TEST.EVAL_EPOCH 10 SOLVER.SCHEDULER 'cosine-refine' SOLVER.MIN_INDEX 0.00001 SOLVER.COSINE_EPOCHS 30 SOLVER.SEED $i

  echo "===> 第 $i 轮训练开始 训练: dataset = regdb"
# RegDB 不加 proxy domain 到第53了 加proxy domain 到4了 该5
  python train_adr.py --config_file configs/RegDB/RegDB_adr.yml MODEL.DEVICE_ID "('0')" OUTPUT_DIR 'logs/regdb_ADR' SOLVER.BASE_LR 0.01 SOLVER.EVAL_PERIOD 1 INPUT.AUG 2 \
  INPUT.SIZE_TRAIN [256,128] INPUT.SIZE_TEST [256,128] MODEL.MSEL True MODEL.MSEL_EPOCH 20 DATASETS.SAMPLER 'modal' MODEL.MSEL_MODAL True DATALOADER.NUM_INSTANCE 8 \
  MODEL.USE_PROMPT True MODEL.NUM_TOKEN 16 MODEL.PROMPT_SCALE 20.0 MODEL.PROMPT_SHIFT 0.0 MODEL.USE_INS_PROMPT True MODEL.USE_INS_PROMPT_GEN True MODEL.NUM_INS_PMT_TOKEN 16 \
  SOLVER.WEIGHT_IPLR 15.0 SOLVER.WEIGHT_MPLR 5.0 MODEL.IPIL False SOLVER.MAX_EPOCHS 120 TEST.EVAL_EPOCH 10 SOLVER.SCHEDULER 'cosine-refine' SOLVER.MIN_INDEX 0.00001 SOLVER.COSINE_EPOCHS 40 SOLVER.SEED $i




  echo "==============================="
  echo ">>> 第 $i 轮训练完成 <<<"
  echo "==============================="
  echo ""
done

echo "===> 所有轮次训练完成 ✅"


# RegDB
#  python train_adr.py --config_file configs/RegDB/RegDB_prior.yml MODEL.DEVICE_ID "('0')" OUTPUT_DIR 'logs/regdb_adr' SOLVER.BASE_LR 0.01 SOLVER.EVAL_PERIOD 1 INPUT.AUG 2 \
#  INPUT.SIZE_TRAIN [256,128] INPUT.SIZE_TEST [256,128] MODEL.MSEL True MODEL.MSEL_EPOCH 20 DATASETS.SAMPLER 'modal' MODEL.MSEL_MODAL True DATALOADER.NUM_INSTANCE 8 \
#  MODEL.USE_PROMPT True MODEL.NUM_TOKEN 16 MODEL.PROMPT_SCALE 20.0 MODEL.PROMPT_SHIFT 0.0 MODEL.USE_INS_PROMPT True MODEL.USE_INS_PROMPT_GEN True MODEL.NUM_INS_PMT_TOKEN 16 \
#  SOLVER.WEIGHT_IPLR 15.0 SOLVER.WEIGHT_MPLR 5.0 MODEL.IPIL False SOLVER.MAX_EPOCHS 120 TEST.EVAL_EPOCH 10 SOLVER.SCHEDULER 'cosine-refine' SOLVER.MIN_INDEX 0.00001 SOLVER.COSINE_EPOCHS 40

