#!/bin/bash

# 权重列表
weights=(0.05 0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1.0 2.0 3.0 4.0 5.0)


for (( i=3; i<90; i++ )) do
    echo "==== Round $i : Training on RegDB ===="

    idx=$(( i % 15 ))
    val=${weights[$idx]}

    # 决定要调整哪个权重
    case $(( i / 5 % 3 )) in
        0)
          echo "Adjusting weight_PHYS to $val"
          python train_adr.py --config_file configs/RegDB_P/RegDB_adr.yml MODEL.DEVICE_ID "('0')" OUTPUT_DIR "logs_P/para_1.0_${val}_1.0" SOLVER.BASE_LR 0.01 SOLVER.EVAL_PERIOD 1 INPUT.AUG 2 \
          INPUT.SIZE_TRAIN [256,128] INPUT.SIZE_TEST [256,128] MODEL.MSEL True MODEL.MSEL_EPOCH 20 DATASETS.SAMPLER 'modal' MODEL.MSEL_MODAL True DATALOADER.NUM_INSTANCE 8 \
          MODEL.USE_PROMPT True MODEL.NUM_TOKEN 16 MODEL.PROMPT_SCALE 20.0 MODEL.PROMPT_SHIFT 0.0 MODEL.USE_INS_PROMPT True MODEL.USE_INS_PROMPT_GEN True MODEL.NUM_INS_PMT_TOKEN 16 \
          SOLVER.WEIGHT_IPLR 15.0 SOLVER.WEIGHT_MPLR 5.0 MODEL.IPIL False SOLVER.MAX_EPOCHS 120 TEST.EVAL_EPOCH 10 SOLVER.SCHEDULER 'cosine-refine' SOLVER.MIN_INDEX 0.00001 SOLVER.COSINE_EPOCHS 40 SOLVER.SEED 3 \
          SOLVER.WEIGHT_MOD 1.0  SOLVER.WEIGHT_PHYS $val SOLVER.WEIGHT_ADR_PROXY  1.0
            ;;

        1)
          echo "Adjusting weight_ADR to $val"
          python train_adr.py --config_file configs/RegDB_P/RegDB_adr.yml MODEL.DEVICE_ID "('0')" OUTPUT_DIR "logs_P/para_1.0_1.0_${val}" SOLVER.BASE_LR 0.01 SOLVER.EVAL_PERIOD 1 INPUT.AUG 2 \
          INPUT.SIZE_TRAIN [256,128] INPUT.SIZE_TEST [256,128] MODEL.MSEL True MODEL.MSEL_EPOCH 20 DATASETS.SAMPLER 'modal' MODEL.MSEL_MODAL True DATALOADER.NUM_INSTANCE 8 \
          MODEL.USE_PROMPT True MODEL.NUM_TOKEN 16 MODEL.PROMPT_SCALE 20.0 MODEL.PROMPT_SHIFT 0.0 MODEL.USE_INS_PROMPT True MODEL.USE_INS_PROMPT_GEN True MODEL.NUM_INS_PMT_TOKEN 16 \
          SOLVER.WEIGHT_IPLR 15.0 SOLVER.WEIGHT_MPLR 5.0 MODEL.IPIL False SOLVER.MAX_EPOCHS 120 TEST.EVAL_EPOCH 10 SOLVER.SCHEDULER 'cosine-refine' SOLVER.MIN_INDEX 0.00001 SOLVER.COSINE_EPOCHS 40 SOLVER.SEED 3 \
          SOLVER.WEIGHT_MOD 1.0  SOLVER.WEIGHT_PHYS 1.0 SOLVER.WEIGHT_ADR_PROXY  $val
            ;;
        2)
          echo "Adjusting weight_MOD to $val"
        # RegDB 不加 proxy domain 到第53了 加proxy domain 到4了 该5
          python train_adr.py --config_file configs/RegDB_P/RegDB_adr.yml MODEL.DEVICE_ID "('0')" OUTPUT_DIR "logs_P/para_${val}_1.0_1.0" SOLVER.BASE_LR 0.01 SOLVER.EVAL_PERIOD 1 INPUT.AUG 2 \
          INPUT.SIZE_TRAIN [256,128] INPUT.SIZE_TEST [256,128] MODEL.MSEL True MODEL.MSEL_EPOCH 20 DATASETS.SAMPLER 'modal' MODEL.MSEL_MODAL True DATALOADER.NUM_INSTANCE 8 \
          MODEL.USE_PROMPT True MODEL.NUM_TOKEN 16 MODEL.PROMPT_SCALE 20.0 MODEL.PROMPT_SHIFT 0.0 MODEL.USE_INS_PROMPT True MODEL.USE_INS_PROMPT_GEN True MODEL.NUM_INS_PMT_TOKEN 16 \
          SOLVER.WEIGHT_IPLR 15.0 SOLVER.WEIGHT_MPLR 5.0 MODEL.IPIL False SOLVER.MAX_EPOCHS 120 TEST.EVAL_EPOCH 10 SOLVER.SCHEDULER 'cosine-refine' SOLVER.MIN_INDEX 0.00001 SOLVER.COSINE_EPOCHS 40 SOLVER.SEED 3 \
          SOLVER.WEIGHT_MOD $val SOLVER.WEIGHT_PHYS 1.0 SOLVER.WEIGHT_ADR_PROXY  1.0

            ;;

    esac

done


#          python train_adr.py --config_file configs/RegDB_P/RegDB_adr.yml MODEL.DEVICE_ID "('0')" OUTPUT_DIR "logs_P/para_3.0_1.0_1.0" SOLVER.BASE_LR 0.01 SOLVER.EVAL_PERIOD 1 INPUT.AUG 2 \
#          INPUT.SIZE_TRAIN [256,128] INPUT.SIZE_TEST [256,128] MODEL.MSEL True MODEL.MSEL_EPOCH 20 DATASETS.SAMPLER 'modal' MODEL.MSEL_MODAL True DATALOADER.NUM_INSTANCE 8 \
#          MODEL.USE_PROMPT True MODEL.NUM_TOKEN 16 MODEL.PROMPT_SCALE 20.0 MODEL.PROMPT_SHIFT 0.0 MODEL.USE_INS_PROMPT True MODEL.USE_INS_PROMPT_GEN True MODEL.NUM_INS_PMT_TOKEN 16 \
#          SOLVER.WEIGHT_IPLR 15.0 SOLVER.WEIGHT_MPLR 5.0 MODEL.IPIL False SOLVER.MAX_EPOCHS 120 TEST.EVAL_EPOCH 10 SOLVER.SCHEDULER 'cosine-refine' SOLVER.MIN_INDEX 0.00001 SOLVER.COSINE_EPOCHS 40 SOLVER.SEED 3 \
#          SOLVER.WEIGHT_MOD 3.0  SOLVER.WEIGHT_PHYS 1.0 SOLVER.WEIGHT_ADR_PROXY  1.0